# version format
version: 1.0.{build}

# Build worker image (VM template)
image: Ubuntu2004

# Env Setup
environment:
  nodejs_version: '16.20.2'

install:
  - nvm install $nodejs_version
  - npm ci

build: off
test: off
